#!/usr/bin/env bash
printf 'running test suite at %s\n\n' "$(date)"

verbose=0

while getopts "v" opt; do
    case "$opt" in
        v) verbose=1 ;;
        ?) exit 1 ;;
    esac
done
shift $((OPTIND - 1))

start=$(date +%s)

TESTDIR=$(pwd)/tests
XR0=$(pwd)/bin/0v
LIBX=$(pwd)/libx
IGNORE_FILE=$TESTDIR/wmw-www

ntests=0
npass=0

expected_suffix="EXPECTED"
fail_prefix="FAIL"
topological_folder="topological"
main_func="main"

fail="\e[31mFAIL\e[0m\n"
pass="\e[32mPASS\e[0m\n"
ignore="\e[33mSKIP\e[0m\n"

run_cmd() {
	f=$1
	folder=$(dirname "$f")
	tempfile=$2

	args=""
	args_file=$folder/args
	if [ -f $args_file ]; then
		args=$(cat $args_file)
	fi
	echo $XR0 -I $LIBX $args $f >> /tmp/args

	$XR0 -I $LIBX $args $f > "$tempfile" 2>&1
}

run_test() {
	f=$1
	folder=$(dirname "$f")
	tempfile=$2

	output=$(run_cmd $f $tempfile)

	# cases where we have an expected output to compare with
	if [[ "$f" == *"${fail_prefix}"* || "$folder" == *"$topological_folder"* ]]
	then
		expected_file="${f}.${expected_suffix}"
		
		echo "$(<$tempfile)" | diff - $expected_file
	else
		# silence is golden
		cat $tempfile
	fi
}

nignore=0
ignore_patterns=$(cat $IGNORE_FILE)

should_ignore() {
    for pattern in $ignore_patterns; do
        if printf '%s\n' "$1" | grep -E -q "$pattern"; then
            return 0
        fi
    done
    return 1
}

cd $TESTDIR/0v

ntests=$(ls */*.x | wc -l)

length=$(ls */*.x | awk '{ print length, $0 }' | sort -n -s | cut -d' ' -f2- |
	tail -1 | wc -c)

# loop through and run tests
for f in */*.x
do
	# skip ignores
	if should_ignore $f; then
		if [ "$verbose" -eq 1 ]; then
			printf "%-${length}s ...$ignore" "$f"
		fi
		nignore=$(($nignore+1))
		continue
	fi

	printf "%-${length}s ..." "$f"

	tempfile=$(mktemp)
	succ=$(run_test $f $tempfile)
	if [[ $succ -eq 0 ]]; then
		npass=$((npass+1))
		printf "$pass"
	else
		printf "$fail"
	fi
	rm $tempfile

done

cd $TESTDIR
cd ..

# source to preserve variables
. $TESTDIR/0db/run

nfail=$((ntests-(npass+nignore)))
finish=$(date +%s)
time=$(echo "$finish-$start" | bc)
printf "\n%d tests:\t%d passed\t%d failed\t%d skipped\tin %d seconds\n" \
	$ntests $npass $nfail $nignore $time
if [ $nfail -ne 0 ]
then
	exit 1
fi
