#!/bin/bash

set +x

XR0=$(pwd)/bin/0v
LIBX=$(pwd)/libx

TESTDIR=$(pwd)/tests/0db/00-basic

output=$($XR0 -I $LIBX -d@ $TESTDIR/test.x < $TESTDIR/test.cfg 2>&1)

tempdir=$(mktemp -d)

# Split the output by the delimiter "(0db)" and write each part to a file
# Using awk to process the splitting and file writing
echo "$output" | awk -v file_prefix="$tempdir/" '
BEGIN { RS="@"; count=0 }  # Set the record separator and initialize the counter
{
    # trim leading and trailing whitespace
    gsub(/^[ \t\r\n]+|[ \t\r\n]+$/, "", $0)
    
    if (length($0) > 0) {   # Check if the line is non-empty
        filename = file_prefix count  # Generate a filename with incrementing counter
        print > filename                      # write the current record to the gen filename
        close(filename)                       # close the file to flush the output
        count++                               # increment the counter for the next file
    }
}'

diff -r $tempdir $TESTDIR/expected && rm -rf $tempdir
